### ISSUE TITLE
Unable to execute checkScriptContent bash script when executing it in GCP

### ISSUE THREAD

**Issue by arunkarepu** [GoogleCloudPlatform/marketplace-tools#36]
I am trying to put one solution in marketplace. I have created a image for the same and using [this ](https://github.com/GoogleCloudPlatform/marketplace-tools/blob/master/docs/mpdev-reference.md) for testing. Here is the [yaml file](https://docs.google.com/document/d/1x3j6uF5DNTLvAn3qmqa3FOUGlCdzUDbq6VbEnH2S1rc/edit?usp=sharing)

Problem is I am trying to check status of a url using 'checkScriptContent' under 'waiter' but it is unable to execute that statement even though it is successfully coming under check_success in GCP. I tried with simple 'return 0' but it is unable to execute it. After checking for 'waiterTimeoutSecs' seconds, it is showing error 'Timed out'. Can you please help me. 
`check_success() (
      EXT_IP=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip); if curl -s --head  --request GET http://$EXT_IP/docs/ | grep "200 OK" > /dev/null; then return 0; else return 1; fi)`

**Comment by gibbleyg** [comment]
Hi, for your example with `return 0` you want that to be `exit 0`

```
return  0
echo $?
line 1: return: can only `return' from a function or sourced script
2
```
