### ISSUE TITLE
Wordpress Terraform example is not working - split function invalid value

### ISSUE THREAD

**Issue by rickyhoth** [GoogleCloudPlatform/marketplace-tools#77]
Dear GCP team,

I found the wordpress TF example is not working when I test it with my Marketplace test listing for UI deployment, it cannot create the  firewall rules with the error "invalid CIDR range". It looks like the issue is on the split function of "tcp_80_ip_source_ranges_map" and "tcp_443_ip_source_ranges_map".

 tcp_80_ip_source_ranges_map = var.enable_tcp_80 ? {
    "80" = split(var.tcp_80_ip_source_ranges, ",")
  } : {}

  tcp_443_ip_source_ranges_map = var.enable_tcp_443 ? {
    "443" = split(var.tcp_443_ip_source_ranges, ",")
  } : {}

The split function should be like split("{separator}", "{string}") instead of split("{string}", "{separator}"), so the revised version should look like this:

  tcp_80_ip_source_ranges_map = var.enable_tcp_80 ? {
    "80" = split(",", var.tcp_80_ip_source_ranges)
  } : {}

  tcp_443_ip_source_ranges_map = var.enable_tcp_443 ? {
    "443" = split(",", var.tcp_443_ip_source_ranges)
  } : {}

Reference: https://developer.hashicorp.com/terraform/language/functions/split

Best Regards,
Ricky

**Comment by gibbleyg** [comment]
Thanks for the report here, we've actually updated the example significantly in https://github.com/GoogleCloudPlatform/marketplace-tools/pull/81, so the example should be working as expected
